version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

dotnet_csproj:

  patch: true

  file: '**\*.csproj'

  version: '{version}'

  package_version: '{version}'

services: mssql2016

before_build:

- cmd: dotnet restore src

build:

  verbosity: minimal

test_script:

- cmd: >-

    cd src/tests

    dotnet xunit